name: Gradle Build

on: [workflow_dispatch]

jobs:
  
  build:

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: tasks
        gradle-version: 7.4

    # - name: 7z
    #   uses: DuckSoft/create-7z-action@v1.0
    #   with:
    #     pathSource: ./build
    #     pathTarget: ./release.7z

    # - name: Upload binaries to release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: release.7z
    #     asset_name: release.7z
    #     tag: ${{ github.ref }}
    #     overwrite: true
