# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildDeb:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bc3340afc5e3cc44f2321809ac090d731c13c514
      with:
        arguments: packageDeb
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux deb artifact
        path: build/compose/binaries/deb
        
  buildDmg:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bc3340afc5e3cc44f2321809ac090d731c13c514
      with:
        arguments: packageDmg
    - name: upload a rtifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS dmg artifact
        path: build/compose/binaries/dmg
        
  buildExe:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bc3340afc5e3cc44f2321809ac090d731c13c514
      with:
        arguments: packageExe
    - name: upload a rtifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows exe artifact
        path: build/compose/binaries/exe
        
