name: Gradle Build

on:
  push:
    branches: [cli]
  pull_request:
    branches: [cli]
jobs:
  
  build:

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: distZip
        gradle-version: 7.4

    # - name: 7z
    #   uses: DuckSoft/create-7z-action@v1.0
    #   with:
    #     pathSource: ./build/distributions/
    #     pathTarget: ./release.7z

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/distributions/tracks-1.0.0.zip
        asset_name: tracks-1.0.0.zip
        tag: ${{ github.ref }}
        overwrite: true
