name: Gradle Build

on:
  push:
    branches: [cli]
    paths:
      - 'src/**'
      - '*.kts'
      - '*.properties'
  pull_request:
    branches: [cli]
    paths:
      - 'src/**'
      - '*.kts'
      - '*.properties'

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - uses: burrunan/gradle-cache-action@v1
      name: Build with Gradle
      with:
        job-id: checker
        arguments: distZip
        gradle-version: wrapper

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: distZip
        path: build/distributions/**/*.zip
